<html>

<head>
    <link href="css/index.css" rel="stylesheet" type="text/css">
</head>


<body>

<div class="main_menu">
    <div id="menu">
        <div id="brand">
            <a href="index.php">
                <div>
                    مشاور املاک
                    نجاتی
                </div>
            </a>
        </div>
        <div class="btns_list">
            <ul style="right: 0">
                <li id="btn_buy">
                    خرید
                </li>
                <li id="btn_rent">
                    اجاره
                </li>
                <li id="btn_sell">
                    فروش
                </li>
                <li id="btn_call">
                    راه های ارتباطی
                </li>
            </ul>
        </div>
        <div class="btns_list" style="float: left">
            <ul style="left: 0">
                <li id="btn_login_signin">
                    ورود / ثبت نام
                    <i class="fa-solid fa-right-to-bracket" style="vertical-align: center; margin-right: 3px"></i>
                </li>
            </ul>
        </div>
    </div>

</div>

<div id="buy_menu" class="menu_bar">
    <div>
        <span>خرید آپارتمان مسکونی</span>
        <span>خرید زمین</span>
    </div>
    <div>
        <span>خرید خانه ویلایی</span>
    </div>
    <div>
        <span>خرید دفتر کار و اداری</span>
    </div>
    <div>
        <span>خرید مغازه و تجاری</span>
    </div>
</div>

<div id="rent_menu" class="menu_bar">
    <div>
        <span>رهن و اجاره آپارتمان مسکونی</span>
        <span>رهن و اجاره خانه کلنگی</span>
    </div>
    <div>
        <span>رهن و اجاره خانه ویلایی</span>
    </div>
    <div>
        <span>رهن و اجاره دفتر کار و اداری</span>
    </div>
    <div>
        <span>رهن و اجاره مغازه و تجاری</span>
    </div>
</div>

<div id="sell_menu" class="menu_bar">
    <div>
        <span>فروش آپارتمان مسکونی</span>
        <span>فروش خانه کلنگی</span>
    </div>
    <div>
        <span>فروش خانه ویلایی</span>
        <span>فروش زمین</span>
    </div>
    <div>
        <span>فروش دفتر کار و اداری</span>
    </div>
    <div>
        <span>فروش مغازه و تجاری</span>
    </div>
</div>


<script src="js/header_menu.js"></script>
</body>
</html>
